### ISSUE TITLE
Using Aptabase with NodeJS?

### ISSUE THREAD

**Issue by sbarre** [aptabase/aptabase-js#5]
It seems the Javascript SDK assumes a browser environment only.

Is there a reason I shouldn't use Aptabase server-side in NodeJS applications or environments?  

We are evaluating Aptabase as a lightweight event tracking system for some of our developer tooling (for a large distributed workforce), and some of these tools are CLIs, APIs and other things that don't run in the browser, but that we would still like to instrument.

Are you intentionally not targeting this use-case for some (valid) reason that escapes me?  

Or could I provide a Node SDK (or a PR to the existing JS one?) as a contribution?

**Comment by goenning** [comment]
No valid reason really not to use it on API/CLIs. It's just that I initially targeted mobile and desktop apps. The dashboard was purposefully built for apps, but should work OK with CLI because you'd also have access to OS Name/Version and Country/Region.

But on an API for example, host OS is irrelevant and Country/Region would always be the same because we extract this from the connection IP. We could however extend the Aptabase API to accept an IP address so the SDK could forward the original IP.

This year I want to make the dashboard more flexible so you can remove widgets that don't matter to you, making it a better fit for pretty much any use case. In case you're self-hosting, that you'd have direct access to the DB and can query it in whatever way you like.

As for this SDK, if possible, extend the existing JS SDK to support nodejs would be my option to avoid  having 2 different SDKs for that.

**Comment by sbarre** [comment]
Ok thanks for the info!   I will think about how to refactor the JS SDK and propose some thoughts here before I go too far, to make sure it's in line with your existing philosophy..   👍
